<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="27439" started-at="2019-08-20T11:41:51Z" finished-at="2019-08-20T11:42:18Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="27439" started-at="2019-08-20T11:41:51Z" finished-at="2019-08-20T11:42:18Z">
      <class name="com.aroha.qa.pages.Datamigration">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.aroha.qa.pages.Datamigration@527740a2]" name="setUp" is-config="true" duration-ms="3778" started-at="2019-08-20T11:41:51Z" finished-at="2019-08-20T11:41:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="Database_Reconciliation_test()[pri:0, instance:com.aroha.qa.pages.Datamigration@527740a2]" name="Database_Reconciliation_test" duration-ms="659" started-at="2019-08-20T11:41:55Z" finished-at="2019-08-20T11:41:55Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Count between source and target not matching expected [8] but found [9]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Count between source and target not matching expected [8] but found [9]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at com.aroha.qa.pages.Datamigration.Database_Reconciliation_test(Datamigration.java:72)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Database_Reconciliation_test -->
        <test-method status="PASS" signature="finalcall()[pri:0, instance:com.aroha.qa.pages.Datamigration@527740a2]" name="finalcall" is-config="true" duration-ms="2" started-at="2019-08-20T11:41:55Z" finished-at="2019-08-20T11:41:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- finalcall -->
      </class> <!-- com.aroha.qa.pages.Datamigration -->
      <class name="com.test.LoginTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.test.LoginTest@13a5fe33]" name="setUp" is-config="true" duration-ms="9551" started-at="2019-08-20T11:41:55Z" finished-at="2019-08-20T11:42:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="Logintest()[pri:0, instance:com.test.LoginTest@13a5fe33]" name="Logintest" duration-ms="12606" started-at="2019-08-20T11:42:05Z" finished-at="2019-08-20T11:42:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Logintest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.test.LoginTest@13a5fe33]" name="tearDown" is-config="true" duration-ms="799" started-at="2019-08-20T11:42:17Z" finished-at="2019-08-20T11:42:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.test.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
